// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package contract_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetPaqueteClient is the client API for GetPaquete service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetPaqueteClient interface {
	LeePaquete(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Paquete, error)
}

type getPaqueteClient struct {
	cc grpc.ClientConnInterface
}

func NewGetPaqueteClient(cc grpc.ClientConnInterface) GetPaqueteClient {
	return &getPaqueteClient{cc}
}

func (c *getPaqueteClient) LeePaquete(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Paquete, error) {
	out := new(Paquete)
	err := c.cc.Invoke(ctx, "/contract_grpc.GetPaquete/LeePaquete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPaqueteServer is the server API for GetPaquete service.
// All implementations must embed UnimplementedGetPaqueteServer
// for forward compatibility
type GetPaqueteServer interface {
	LeePaquete(context.Context, *Empty) (*Paquete, error)
	mustEmbedUnimplementedGetPaqueteServer()
}

// UnimplementedGetPaqueteServer must be embedded to have forward compatible implementations.
type UnimplementedGetPaqueteServer struct {
}

func (UnimplementedGetPaqueteServer) LeePaquete(context.Context, *Empty) (*Paquete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeePaquete not implemented")
}
func (UnimplementedGetPaqueteServer) mustEmbedUnimplementedGetPaqueteServer() {}

// UnsafeGetPaqueteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetPaqueteServer will
// result in compilation errors.
type UnsafeGetPaqueteServer interface {
	mustEmbedUnimplementedGetPaqueteServer()
}

func RegisterGetPaqueteServer(s grpc.ServiceRegistrar, srv GetPaqueteServer) {
	s.RegisterService(&GetPaquete_ServiceDesc, srv)
}

func _GetPaquete_LeePaquete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetPaqueteServer).LeePaquete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract_grpc.GetPaquete/LeePaquete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetPaqueteServer).LeePaquete(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GetPaquete_ServiceDesc is the grpc.ServiceDesc for GetPaquete service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetPaquete_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract_grpc.GetPaquete",
	HandlerType: (*GetPaqueteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeePaquete",
			Handler:    _GetPaquete_LeePaquete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contratos.proto",
}
