apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: default
spec:
  rules:
  - host: ec2-52-10-163-115.us-west-2.compute.amazonaws.com  
    http:
      paths:
      - pathType: Prefix
        path: "/paquete"
        backend:
          service:
            name: paquete
            port:
              number: 9000

